FROM golang:1.19-alpine

RUN mkdir /app

ADD . /app

WORKDIR /app

COPY ./go.mod ./
COPY ./deployment/sit.env ./.env

RUN go mod download
RUN go install github.com/swaggo/swag/cmd/swag@latest
RUN go get -u github.com/swaggo/gin-swagger
RUN go get -u github.com/swaggo/files

RUN swag init

RUN go build -o main .

CMD ["/app/main"]